### ISSUE TITLE
Verify initial config of 9500 model matched what is needed for app evaluation

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1146]
Initial config is described in this file: [App evaluation events file](https://app.zenhub.com/files/73223031/bca522ab-781c-468d-872e-9eaaffaf0524/download)

**Comment by singha42** [comment]
Compared the initial config components in the XML. Attached is the result.
[bca522ab-781c-468d-872e-9eaaffaf0524 (3).xlsx](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/3785432/bca522ab-781c-468d-872e-9eaaffaf0524.3.xlsx)

**Comment by temcdrm** [comment]
Shiva has a candidate fix for the generators not present in the XML.  This happened because they were "disabled" in OpenDSS.  Instead, they have to be "enabled" but at zero output for the CIM export.  See https://github.com/GRIDAPPSD/Powergrid-Models/pull/55 but that has to be merged with the SWING_PQ branch first: https://github.com/GRIDAPPSD/Powergrid-Models/tree/issue/1147

**Comment by poorva1209** [comment]
@temcdrm Does issue/1147 branch solves the island creation issue for evaluation or more work would be needed? You can edit the pull request and change the base branch from develop to issue/1147 for Shiva's pull request.

**Comment by singha42** [comment]
All switches and generators are present in the updated XML. Attached is the result.
[bca522ab-781c-468d-872e-9eaaffaf0524.3.xlsx](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/3806226/bca522ab-781c-468d-872e-9eaaffaf0524.3.xlsx)
