### ISSUE TITLE
Write a SWING_PQ node for each potential island

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1147]

**Comment by shpoudel** [comment]
@poorva1209 
These are the nodes with DERs which can form islands as described in the event file if they are assigned as swing bus: m1209-DIES1, m1142-lng1, m2001-mt1

**Comment by temcdrm** [comment]
There is no DER connected to m1209-dies1 or m1142-lng1.  There are diesels on m1026chp-3, m1069-mt1, m2001-mt1 and m1047pv-3.  There are batteries on m2001-ess1 and m2001-ess2.

**Comment by shpoudel** [comment]
@temcdrm The Diesel and LNG engine at m1209-dies1 and m1142-lng1 are disabled for the initial condition. However, while simulating events, they need to be enabled for forming islands. So, as per my understanding, they are physically present there (Generators.dss) but not supplying any loads in normal conditions (Enabled=0). However, when required, can be made online using enabled = True/ False in OpenDSS to simulate these scenarios.

**Comment by temcdrm** [comment]
Anything disabled is not written to CIM.  You have to leave them enabled, but dialed down.

**Comment by shpoudel** [comment]
If we enable them, then what are the possible ways to make them down? One way would be to make their output (P=0 and Q = 0) or make their connecting switch open. I don't think either of them will work. Can you please suggest something around this?

**Comment by temcdrm** [comment]
You should be able to make P=0 and Q=0, provided the generators are in a mode (not 3 or 6) where they don't try to regulate voltage.  

Opening their switch could also work, but you can't leave P or Q non-zero in that case.  The first method should be easier.

**Comment by shpoudel** [comment]
Let me summarize the discussion above: 
1. Make DG enabled if you want to form islands with them because they won't appear in CIM with if they are disabled.
2. Make their P = 0 and Q = 0 (No generation during normal conditions as they are costly generation resources, say)
3. Make their connected bus as "busype = SWING_PQ" because we might want to form islands while simulating events if required.
4. Now when islands are created, these generators generate the required power to supply the islands?

Note: The glm file you gave me has all Gen_Type as Constant_PQ irrespective of the modes in OpenDSS. Why is it so?

**Comment by temcdrm** [comment]
1 and 2 are correct as stated.  3 is also correct, but the CIMImporter code changes on this branch will handle it automatically when generating the GridLAB-D file.  4 is also correct, but you will have to re-dispatch the generators to non-zero P and Q before they actually support an island.

Note: GridLAB-D and OpenDSS generator modes are not identical. We're using Constant_PQ in GridLAB-D so that you can (and must) set those values explicitly.

**Comment by shpoudel** [comment]
Just one final comment on #4. 

If it is a swing bus, why would we have to re-dispatch the generators for an island? I am running some experiments in the .glm file you sent me and observed that the generator supplies the island irrespective of the size of the island and generates required P and Q. I believe it is because of swing bus property. Or Am I doing something wrong? Having kVA rating and assigning swing property to the same component is conflicting logically, isn't it?

The only thing app developers should be aware of is the KVA rating of the generator such that the size of an island doesn't exceed the capacity of DGs. Does this make sense, Tom?

**Comment by temcdrm** [comment]
Yes, for the designated swing bus, GridLAB-D will produce whatever P and Q is needed for convergence.  However, this may exceed physical rating of the generator. The app needs to make sure other non-swing DER in the island are dispatched such that the swing bus generation is within rating.  One has to do the same with any power flow solver.

**Comment by shpoudel** [comment]
Thanks, Tom. I was just curious if solvers like GridLAB-D are smart enough to generate a warning or error if a DER assigned as a swing bus has to generate power more than its kVA rating for convergence. 

Now, I am going to enable all the generators and assign P = 0 and Q = 0 for those which were disabled before. Redispatching of these generators will be the job of app developers as per their requirements. 

Thanks again for this conversation.
