### ISSUE TITLE
CimHub Refactoring

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1175]

**Comment by temcdrm** [comment]
Next tasks:

1. Export 6 sub-profiles for the summer 2020 CDPSM interop tests (this was already implemented in OpenDSS)
2. Be able to export the Survalent model in different CIM versions
3. Be able to export a transmission power flow for GridPACK solution.

**Comment by temcdrm** [comment]
The focus now will be to consolidate with Powergrid-Models, so that platform can use CIMHub (with opendsscmd build) rather than Powergrid-Models.

Interop tests have been delayed by external factors.

**Comment by temcdrm** [comment]
The goal of refactoring will be to consolidate the code components in CIMHub, so that the platform would use a CIMHub JAR instead of the CIMImporter JAR in Powergrid-Models. The platform circuits and supporting files would stay in Powergrid-Models.

Powergrid-Models functionality moving to CIMHub:

- ./blazegraph/src
- ./converters
- ./DER
- ./houses
- ./Meas

Functionality staying in Powergrid-Models:

- ./.gradle-wrapper (not sure what this is for)
- ./blazegraph (need to update the testing scripts to use CIMHub's JAR)
- ./blazegraph/support
- ./blazegraph/test (the **ieee9500** source files live here, from which CIMHub publishes them in CIM XML, OpenDSS, GridLAB-D and CSV formats)
- ./CIM (check whether this can be archived)
- ./cnf (not sure what this is for)
- ./glmanip_module (check whether this can be archived)
- ./taxonomy (one taxonomy circuit is used in the platform)

Subdirectories under Powergrid-Models that should be moved to an archive directory:

- ./8500_reduced_nodes
- ./GLM
- ./SmartCity

**Comment by poorva1209** [comment]
@temcdrm Can we close this issue now? Or there is still something remaining to be done?

**Comment by temcdrm** [comment]
Not quite.  I'm working on two pull requests, one for CIMHub and one for Powergrid-Models.  The process of loading feeders, houses and measurements into the platform will change (hopefully, simplified).

**Comment by poorva1209** [comment]
ok, let me know if you need me to work on anything. Otherwise, I will remove my assignment from this task.
