### ISSUE TITLE
State Plotter Default Configuration

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#1256]
Large models include too many states for plots to be meaningful.

Existing capabilities allow (effectively) arbitrary reduction in the number of channels monitored.

We need to determine a meaningful way to select a subset of states to plot.

**Comment by garydblack** [comment]
Got a reasonable implementation of the "statistics" done to show the min, max, mean, and standard deviation of the plot values including even shading of regions.  Also updated the command line options because the use of the term "nominal" wasn't correct and the plot titles and y-axis labels were also updated so all is in good shape.

Therefore, state plotter is in good shape with just a known issue where it will sometimes crash on a specific plot when first starting, presumably because of invalid data being passed to matplotlib, but more investigation is needed to determine what is happening.
