### ISSUE TITLE
Missing VA measurements for Synchronous machine in simulation output

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1345]
### Description of Issue
The measurement mrid associated with **VA** measurements in Synchronous machine has 0 value in simulation output.

**Comment by afisher1** [comment]
I've confirmed that the issue is with GridLAB-D. Seems to be an issue with how diesel_dg which is the object in the gridlabd that gets used is updating the parent meter in a weird way when the parent meter is itself a child object of a node. essentially the node gets the power injections from the generator and bypassed the meter. Working to on a fix now.

**Comment by poorva1209** [comment]
@shpoudel Is this needed for generating historical data?

**Comment by shpoudel** [comment]
@poorva1209 I don't think so. Let's confirm it here.

@afisher1 If the node gets the power injections from the generator, the power flow results should not be affected with this, right? If the meter has an issue, we can still generate the time-series data assuming the power flow is solved correctly. Your thoughts?

**Comment by afisher1** [comment]
correct powerflow results should not be affected. We fixed the issue and updated the GridLAB-D develop branch. I updated my gridappsd container with the latest develop branch of GridLAB-D. I am now getting non-zero VA measurements for the synchronous machines generating power in the 9500 node model.
