### ISSUE TITLE
OES Model - Measurement values for Solar Pv not coming from platform 

### ISSUE THREAD

**Issue by singha42** [GRIDAPPSD/GOSS-GridAPPS-D#1354]
In the Avista model for this particular Solar panel, the measurements are not coming from the platform. 

o	Name:PowerElectronicsConnection_PhotovoltaicUnit_pv1,Phase:A,MeasurementType:VA,ConnectivityNode:pv,SimObject:pv_pvmtr

**Comment by afisher1** [comment]
I saw all the solar measurements present in the model coming out of the bridge so this isn't a simulator issue.

**Comment by singha42** [comment]
If we run the simulation for around 10 mins, the magnitude updates after some time and it becomes zero again.

**Comment by afisher1** [comment]
The model you provided started the simulation at 22:48:12 and ran to 12:41:32 of the next day. So it starts when the sun is down hence why you don't see any output until the sun rises and then I start to see solar panel generation. The reason why you saw output at the very beginning was due to a bug with the generated weather file. the weather file's first value is at 22:49:00 and the last one is at 12:41:00. due to the nature of how the weather file is treated in GridLAB-D it wrapped the last entry around to fill any missing data at the start so for the first minute it was using weather data from the 12:41:00 entry which is in the middle of the day. I've since corrected this by making sure the weather file has input for the entirety of the simulation.
