### ISSUE TITLE
Re-import 9500 node model in blazegraph 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1401]
- Alexander will make sure the data is correct in power grid models

**Comment by shpoudel** [comment]
@AAndersn - I was just curious why we are using wire data and cable data instead of impedances in the updated 9500-node model. For such definitions, OpenDSS and GridLAB-D use two different approaches to calculate the impedance matrix (Deri Vs Carson). The power flow solution might differ if all line segments are defined this way.

**Comment by AAndersn** [comment]
Motivation was to make the model more generic so that it could be loaded into any other program (e.g. ESRI databsed or other vendor software).

Let's talk about it with Tom during Monday work meeting

**Comment by shpoudel** [comment]
Thanks, Alexander. It is not a big issue, I was just curious. I agree with you about making the model more generic.

**Comment by AAndersn** [comment]
PV farm not imported correctly. Addressing under Issue 89.
