### ISSUE TITLE
Make blazegraph namespace consistent between CIMHub and GOSS-GridAPPS-D 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1488]

**Comment by temcdrm** [comment]
Instead of hard-coding into constants.py, this should be handled with a **cimhubconfig.json** file that would be customized for different contexts. For example, from Powergrid-Models/platform, the measurements are inserted as follows:

declare -r CIMHUB_UTILS="../../CIMHub/utils"
python3 $CIMHUB_UTILS/InsertMeasurements.py **cimhubconfig.json** ./Meas/transactive_switch_i.txt ./Meas/transactive_msid.json

_where cimhubconfig.json is_

{
  "blazegraph_url": "http://localhost:8889/bigdata/namespace/kb/sparql",
  "cim_ns": "<http://iec.ch/TC57/CIM100#"
}

If every operation inside the platform is done this way, referencing the same **cimhubconfig.json** file, then everything should remain consistent.
