### ISSUE TITLE
PV/Battery control should be using Inverter ID

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1517]
While controlling the inverter-baser DER, it seems like the bridge is using a device (PV) ID instead of an inverter ID. Did it get change during some update? If I remember correctly, last time it was using Inverter ID.

**Comment by afisher1** [comment]
In order to make this work. models_dict.json would need to provide the list of inverter CIM json structures similar to PV and Batteries so The HELICS_GOSS_BRIDGE knows how to map MRID to simulator object name.

**Comment by craig8** [comment]
@craig8 needs this as well.

**Comment by poorva1209** [comment]
Use PV and battery queries. Add to Power grid model API. @AAndersn Create new  ticket for this.

**Comment by AAndersn** [comment]
Will not change in HELICS Bridge because model_outputs.json file is written using BatteryUnit and PhotovoltaicUnit mRIDs instead of with PowerElectronicsConnection mRID

Created new tickets for adding API queries #1653 and #1654 
Existing documentation ticket https://github.com/GRIDAPPSD/gridappsd-training/issues/7
