### ISSUE TITLE
query battery measurement of simulation output return empty

### ISSUE THREAD

**Issue by xcosmos6** [GRIDAPPSD/GOSS-GridAPPS-D#1609]
### Description of Issue
The model is created specifically for the Soap-Sever project, here is the link how to create the model:
https://github.com/GRIDAPPSD/gridappsd-soap-server/tree/master/circuit

When I start the simulation via the simulation API, I saw the following message:
All measurements for object bat_Bat_WTG are missing from the simulator output.

And when I query the timeseries database via the Timeseries API, the data was a empty list.

**Comment by afisher1** [comment]
The reason the battery measurements are missing is because the base name between what is in CIM and what is in the translated GridLAB-D model_base.glm file are different.  I noticed that the battery name queried from CIM is Bat_WTG. As part of the Powergrid_Models conversion script that object should have the name bat_Bat_WTG in model_base.glm. However, I believe this process is using CIMHUB to do model conversions, correct me if I'm wrong.  This conversion process ends up creating the object in model_base.glm as bat_Bat_WTG_Battery. I also noticed that all created batteries and their inverter objects have the _Battery suffix attached to their names. I also noticed that all solar and their inverters have an unexpected _Photovoltaic suffix attached to their names.  So in addition to the GridLAB-D helics config having the mismatched names for battery measurements any inverter commands sent by apps will fail to be parsed correctly as well. 

As a test I ran the 9500 model which has battery and PV objects which use the conversion script contained in Powergrid_Models repo. There are no _Battery and _Photovoltaic suffixes attached to the names of those objects. So my assumption is that CIMHUB is being used to create the GridLAB-D model and adds the erroneous suffixes.
