### ISSUE TITLE
Validate CIM profiles using a tool before adding to platform

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#222]
We can use CIM Tool for this if it provides executable or search something else

**Comment by ericstephan** [comment]
It would be good to connect with @telsethag and myself based on the RDF/SHACL validation tools we are using for the time-series data.

**Comment by temcdrm** [comment]
Just pushed RC1.owl and CIM_Tutorial.pptx under Powergrid-Models/CIM.  These show how CIMTool can be installed and used to validate an XML file in the CIMTool GUI, before importing into the workspace.

Currently, we are using CIM17.  The XML files won't validate against RC1.owl, because it's based on CIM16. Tom will create a new OWL for RC4, based in CIM17 extended.

Todd and Eric will investigate a command-line use of SHACL to validate CIM XML files using the OWL files for GridAPPS-D.  In the meantime, Tara (or whomever) could use CIMTool to perform a GUI validation based on the OWL files.  CIMTool is an Eclipse plug-in, hence not a lightweight installation.  On the other hand, a GUI CIMTool validation only need to be done the first time we see a new CIM XML file, before loading into Blazegraph.  This won't have to be done each time the platform starts, nor even during the docker-based installation.

**Comment by temcdrm** [comment]
Tara or Poorva, please review this issue and then make two new ones:

1) updated OWL file for RC4 validation (Tom)
2) command-line validation process using SHACL (Todd and Eric)

**Comment by temcdrm** [comment]
At the apps developer meeting August 28, we agreed to defer this until after the September demo, because it will involve adoption of CIM100, which in turn will induce changes to SPARQL queries, measurements, the CIMImporter and OpenDSS. At this time, the profile for CIM100 has been constructed in CIMTool.  Stopgap measures required for the September demo have been implemented, in particular, the default inverter mode for GridLAB-D is now CONSTANT_PQ, which is compatible with NREL's app dispatching P and Q

**Comment by temcdrm** [comment]
Closing this in favor of new sub-issues.
