### ISSUE TITLE
PV inverter output values from gridlabd are too high. 

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#703]
### Description of Issue
This is for the IEEE123 feeder that we built and converted to CIM.

The PV inverter output values from gridlabd are sometimes too high. 
For example the inverter  "inv_dg_72_PVPanels" the  rated_power is 280000.
But the output from gridlabd is 509970. 
This in not the case for all the inverters. dg_90 gives the correct values for example.

Please see the include output file and model included.

[ieee123_1830864237.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/2447872/ieee123_1830864237.zip)

I also include the IEEE13 model which give high values for the "school", but the "house"  is correct. 
[ieee13_2022850817.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/2447869/ieee13_2022850817.zip)

**Comment by temcdrm** [comment]
Loads, batteries and solar PV measurements are all separated. Houses were also tested and verified to run with the 8500-node and taxonomy feeders. Required:

- reload the R2 taxonomy feeder into the platform
- load the ieee123pv model into the platform (can generate the xml from powergrid-models/blazegraph/test/dss)
- pull and build feature/1146 of GridLAB-D

The house inserter generates thermostat setpoints that violate GridLAB-D's requirement of heating<(cooling-deadband). Setpoint violations also occur when the heating type is NONE but the cooling type is not, because in that case GridLAB-D overrides the heating to be RESISTANCE with a default setpoint of 68 degrees. These are corrected in the CIMImporter when it generates GLM files.  The house inserter also creates unrealistic setpoints on the tails of the distribution, e.g. a cooling setpoint of 50 degrees.  These were left untouched but the app developer should reevaluate.

**Comment by afisher1** [comment]
This behavior was due to the measurements for the pv being performed on meters that were not dedicated to just those pv's. This has been corrected and tests using NREL's application.
