### ISSUE TITLE
Format state estimator output

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#757]

**Comment by areiman** [comment]
The state estimator output will consist of voltage magnitudes and phases. This is the same basic content as a voltage measurement; however, measurement messages include an mrid of the measurement object.

State estimates are not the same as measurements so the state estimator cannot update the values of existing measurements. Furthermore, a system is not guaranteed to have existing voltage measurement objects for all buses. 

If the state estimator is to add new measurement objects to the model to obtain mrids for each of its estimates, it will be necessary to make sure that other applications can distinguish state estimator "measurements" from true system measurements. In addition, the burden of requiring downstream apps to query "measurement"/"estimate" objects to decode any mrid included in the state estimator output should be considered.

This a separate issue from discussion around the distinction between "physical" measurements (corresponding to modeled sensors) and "virtual" measurements (currently necessary for the platform to publish the complete system output).

**Comment by areiman** [comment]
From Tom:
1)	Please see the lower left of the UML in Figure 11 here: https://gridappsd.readthedocs.io/en/master/developer_resources/index.html#class-diagrams-for-the-profile
2)	Andy’s state variables are always voltages, and can be expressed as SvVoltage instances associated to the ConnectivityNode (i.e., not a Terminal). 
3)	There will be one SvVoltage per phase. We already had WG13 add all those phase attributes to StateVariables in order to support this.
4)	However, WG13 would not add SvCurrent because it looks redundant with SvPowerFlow + SvVoltage, if you’re only concerned with expressing a power flow solution. This would be an issue for those using branch currents for state estimator state variables, as many do on distribution systems.  It’s not an issue for us, because we’re using voltages.  But it’s an example of how WG13 might not modify StateVariables just to support state estimation.
5)	The StateVariables package has no conception of errors or residuals.  We’ll need to add that for state estimation.
6)	The StateVariables package has no conception of different times or synchronicities of the estimates.  We may need to add that for state estimation.  There is a mechanism to collect information into a Steady-State Hypothesis (SSH) but that might not serve our needs.
7)	Agreed that the StateVariable and Measurement mRIDs are going to be different.

Suggested path forward:

1)	Andy Reiman figures out what’s needed for errors, timing, etc.
2)	Eric uses that to pose a question to ENTSO-E; i.e., how do they handle similar issues that are specific to state estimators, rather than power flow solutions?
3)	We then implement the extensions, and possibly propose them to WG13 when we’re sure they work.

**Comment by areiman** [comment]
Example state estimator output message (does not currently include ConnectivityNode name):

{
    “simulation_id” : “2017556843”,
    “message” : {
        “timestamp” : 1248159611,
        “svvoltages” : [
            {
                “v” : 2401.78,
                “angle” : 0.0,
                “phase” : A,
                “connectivitynode” : _35CCFFEB-1F1B-BCC3-8853-C1B8015EF365”
             },
            {
                “v” : 2401.78,
                “angle” : 120.0,
                “phase” : C,
                “connectivitynode” : “_35CCFFEB-1F1B-BCC3-8853-C1B8015EF365”
            }
        ]
    }
}

**Comment by areiman** [comment]
Proposed CIM extension:
New Class: SvVoltage::SvEstVoltage
+ vVariance: Voltage
+ angleVariance: AngleDegrees

New Class Estimate
+ timeStamp: DateTime
