### ISSUE TITLE
Add explicit option for manual/remote control of capacitors and regulators

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#863]
### Description of Issue
Currently, the fncs_goss_bridge doesn't have an explicit way to set regulators and capacitors to `MANUAL` control.

Relevant section for capacitors:
```python
            if cim_attribute == "RegulatingControl.mode":
                val = x.get("value")
                if val == 0:
                    fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0]] = "VOLT"
                elif val == 2:
                    fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0]] = "VAR"
                elif val == 3:
                    fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0]] = "CURRENT"
                else:
                    fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0]] = "MANUAL"
                    _send_simulation_status("RUNNING", "Unsupported capacitor control mode requested. The only supported control modes for capacitors are voltage, VAr, volt/VAr, and current. Setting control mode to MANUAL.","WARN")
```
Relevant section for regulators:
```python
            elif cim_attribute == "TapChanger.lineDropCompensation":
                if x.get("value") == 1:
                    val = "LINE_DROP_COMP"
                else:
                    val = "MANUAL"
                fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0]] = "{}".format(val)
```
Notice that these are implicit rather than explicit.

### Proposed solution
It appears a CIM extension may be in order here. There is no "manual" entry for RegulatingControlModeKind. Note that really, we want "remote control," the "manual" language is just for GridLAB-D.

As far as code in the fncs_goss_bridge:
capacitors:
Simply add an explicit case for MANUAL.
regulators:
Changing 'TapChanger.lineDropCompensation' is way too explicit. There should be a way to change the control mode otherwise.

NOTE: The way the fncs_goss_bridge is currently written is slightly problematic: The if statement ```if cim_attribute == "RegulatingControl.mode":``` is currently only used for capacitors, but really should be used for regulators as well. The issue is that GridLAB-D has different control modes for regulators vs. capacitors.

@afisher1 @temcdrm @poorva1209

**Comment by poorva1209** [comment]
We are making changes in Viz app and fncs_goss_bridge to add RegulatingControl attribute enabled-disabled for manual control.

**Comment by temcdrm** [comment]
See Figure 7 for tap changers and Figure 5 for capacitors here: https://gridappsd.readthedocs.io/en/master/developer_resources/index.html#class-diagrams-for-the-profile

For the purpose of this discussion, "manual" control is accomplished by human command, either in the field or from the operation center.  The other methods are by local autonomous control, as enumerated in RegulatingControlModeKind. 

For capacitors, just set the associated RegulatingControl.enabled to False for manual control.  If there is no associated RegulatingControl, that also implies manual control. In either case, change ShuntCompensator.sections to manually switch the capacitors.  (NOTE: we should add ShuntCompensatorPhase.sections as well to the CIM, so that a capacitor bank with individual phase control can have different number of sections used in each phase).

For tap changers, we should also just set the associated RegulatorControl.enabled to False for manual control, and then change TapChanger.step to move the tap manually.  Note that TapChangerControl inherits from RegulatorControl, and if there isn't one associated to a TapChanger, that implies manual control.  (NOTE: the CIM provides a redundant way to specify manual control for tap changers that have existing controllers, by setting TapChanger.controlEnabled to False. But that's not consistent with the only available pattern for capacitors. Nor is it needed to determine whether a control exists, because we simply check for the existence of associated RegulatingControl, as with capacitors. Therefore, we should remove TapChanger.controlEnabled from the GridAPPS-D profile. Otherwise, we might end up having to interoperate with both mechanisms.)

No need to expand the RegulatingControlModeKind enumeration.  Poorva has the right idea. Adding Eric to review for CIM profile changes:

- add ShuntCompensatorPhase.sections
- remove TapChanger.controlEnabled from the profile and the CIMImporter

**Comment by blthayer** [comment]
@temcdrm, @afisher1, @poorva1209, @ericstephan - I was taking a look at fncs_goss_bridge.py, and it doesn't seem that these changes have been implemented: there's no instance of regulatingControl.enabled in the file.

Can we get this fix in soon? I think it makes sense for any application that's controlling regulators/capacitors to set them to manual mode as a very early step in application initialization.

**Comment by blthayer** [comment]
@poorva1209 @afisher1 giving this ticket a bump. It looks like the milestone field probably needs updated.

**Comment by poorva1209** [comment]
This is done in develop branch and would be included in the current release due Monday.
