### ISSUE TITLE
Add fault documentation on readthedocs

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#907]

**Comment by AAndersn** [comment]
@Jeffrey-Simpson , please take a look at

https://gridappsd-training.readthedocs.io/en/develop/installation/1.5--Lesson-1.5--Using-GridAPPS-D-Viz.html#2.4.2.-Equipment-Faults

**Comment by Jeffrey-Simpson** [comment]
Okay will do. Are you looking for specific examples or test manager details?

I have some documentation for events in this repo/branch for the test manager.
https://github.com/Jeffrey-Simpson/gridappsd-docs/tree/1523/docs/source/using_gridappsd

***@***.***D77404.E3E47390]

Thanks,
-Jeff

From: Alexander Anderson ***@***.***>
Reply-To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Date: Thursday, July 8, 2021 at 12:23 PM
To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Cc: "Simpson, Jeff" ***@***.***>, Mention ***@***.***>
Subject: Re: [GRIDAPPSD/GOSS-GridAPPS-D] Add fault documentation on readthedocs (#907)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@Jeffrey-Simpson<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffrey-Simpson&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C401f063756ca42511c0e08d9423d8189%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637613654204416389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zH4V7zNPKw3YTLOle66uqldx4tmMjqkBlGeyU8snpfo%3D&reserved=0> , please take a look at

https://gridappsd-training.readthedocs.io/en/develop/installation/1.5--Lesson-1.5--Using-GridAPPS-D-Viz.html#2.4.2.-Equipment-Faults<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgridappsd-training.readthedocs.io%2Fen%2Fdevelop%2Finstallation%2F1.5--Lesson-1.5--Using-GridAPPS-D-Viz.html%232.4.2.-Equipment-Faults&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C401f063756ca42511c0e08d9423d8189%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637613654204416389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T6M9XGGBPjAK3zqfIshwSs1ttgriGS2AcJnEI7FSLj4%3D&reserved=0>

**Comment by AAndersn** [comment]
@Jeffrey-Simpson , thanks for passing this along.

I will merge in the diagrams on https://github.com/Jeffrey-Simpson/gridappsd-docs/blob/1523/docs/source/using_gridappsd/test_manager_events.rst and ping you when ready to review and close this ticket

**Comment by AAndersn** [comment]
@Jeffrey-Simpson I have built a detailed Test Manager section using your updates in the Simulation API page:

https://gridappsd-training.readthedocs.io/en/develop/api_usage/3.5-Creating-Running-Simulation-API.html#Test-Manager-Configuration

Please review and close if it looks good

**Comment by Jeffrey-Simpson** [comment]
Hello,

I updated the diagram to make some name changes and I changed FaultMRID to faultMRID in 2 places in the text. So that should be updated.
And if  you grab the new diagram from here https://github.com/Jeffrey-Simpson/gridappsd-docs/blob/1523/docs/source/using_gridappsd/test_manager_events.rst
That would be good too.

Also if you could change this:
"test_config": {
    "outageEvents": [
        {
            "event_type": "CommOutage",
            "tag": "unique_tag",
            "startDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYY-MM-DD HH:MM:SS" OR epoch time number,
            "allInputOutage": true or false,
            "inputList": [
                {
                    "name": "equipment name",
                    "type": "CIM equipment type",
                    "mRID": "equipment object mRID",
                    "phases": [
                        {
                            "phaseLabel": "A" or "B" or "C",
                            "phaseIndex": number
                        }
                    ],
                    "attribute": "CIM Control Attribute"
                }
            ],
            "allOutputOutage": true or false,
            "outputList": [
                {
                    "name": "equipment name",
                    "type": "CIM equipment type",
                    "mRID": "equipment object mRID",
                    "phases": [ "A" or "B" or "C"  ],
                    "measurementTypes": [ "PNV" or "VA" or "POS" ]
                }
            ]
        }
    ],
    "faultEvents": [
        {
            "event_type": "Fault",
            "tag": "unique_tag",
            "equipmentType": "CIM object type",
            "equipmentName": "equipment name",
            "mRID": [
                "equipment object mRID",
                "equipment object mRID",
                "equipment objhect mRID"
            ],
            "phases": [
                {
                    "phaseLabel": "A" or "B" or "C",
                    "phaseIndex": number
                }
            ],
            "faultKind": "lineToGround" or "lineToLine" or "lineToLineToGround",
            "faultImpedance": {
                "rGround": "value",
                "xGround": "value"
            },
            "startDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number
        }
    ],
    "commandEvents": [
        {
            "message": {
                "forward_differences": [
                    {
                        "object": "control object mRID",
                        "attribute": "CIM Class Attribute",
                        "value": number
                    }
                ],
                "reverse_differences": [
                    {
                        "object": "control object mRID",
                        "attribute": "CIM Class Attribute",
                        "value": number
                    }
                ]
            },
            "event_type": "ScheduledCommandEvent",
            "occuredDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number
        }
    ]
}

To this to just have one list of events:
"test_config": {
    "events": [
        {
            "event_type": "CommOutage",
            "tag": "unique_tag",
            "startDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYY-MM-DD HH:MM:SS" OR epoch time number,
            "allInputOutage": true or false,
            "inputList": [
                {
                    "name": "equipment name",
                    "type": "CIM equipment type",
                    "mRID": "equipment object mRID",
                    "phases": [
                        {
                            "phaseLabel": "A" or "B" or "C",
                            "phaseIndex": number
                        }
                    ],
                    "attribute": "CIM Control Attribute"
                }
            ],
            "allOutputOutage": true or false,
            "outputList": [
                {
                    "name": "equipment name",
                    "type": "CIM equipment type",
                    "mRID": "equipment object mRID",
                    "phases": [ "A" or "B" or "C"  ],
                    "measurementTypes": [ "PNV" or "VA" or "POS" ]
                }
            ]
        },
        {
            "event_type": "Fault",
            "tag": "unique_tag",
            "equipmentType": "CIM object type",
            "equipmentName": "equipment name",
            "mRID": [
                "equipment object mRID",
                "equipment object mRID",
                "equipment objhect mRID"
            ],
            "phases": [
                {
                    "phaseLabel": "A" or "B" or "C",
                    "phaseIndex": number
                }
            ],
            "faultKind": "lineToGround" or "lineToLine" or "lineToLineToGround",
            "faultImpedance": {
                "rGround": "value",
                "xGround": "value"
            },
            "startDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number
        },
        {
            "message": {
                "forward_differences": [
                    {
                        "object": "control object mRID",
                        "attribute": "CIM Class Attribute",
                        "value": number
                    }
                ],
                "reverse_differences": [
                    {
                        "object": "control object mRID",
                        "attribute": "CIM Class Attribute",
                        "value": number
                    }
                ]
            },
            "event_type": "ScheduledCommandEvent",
            "occuredDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number,
            "stopDateTime": "YYYY-MM-DD HH:MM:SS" OR epoch time number
        }
    ]
}



Thanks,
-Jeff

From: Alexander Anderson ***@***.***>
Reply-To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Date: Tuesday, August 3, 2021 at 9:22 PM
To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Cc: "Simpson, Jeff" ***@***.***>, Mention ***@***.***>
Subject: Re: [GRIDAPPSD/GOSS-GridAPPS-D] Add fault documentation on readthedocs (#907)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@Jeffrey-Simpson<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffrey-Simpson&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467551538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kfs%2BC5RO5L0txhHqWGfHE67sIhG0%2BWxnavSMVSpu6is%3D&reserved=0> I have built a detailed Test Manager section using your updates in the Simulation API page:

https://gridappsd-training.readthedocs.io/en/develop/api_usage/3.5-Creating-Running-Simulation-API.html#Test-Manager-Configuration<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgridappsd-training.readthedocs.io%2Fen%2Fdevelop%2Fapi_usage%2F3.5-Creating-Running-Simulation-API.html%23Test-Manager-Configuration&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467561495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r%2Fmq%2FhpF4hvOLQWXmMG%2FDCAucZNW8REQO7DQhQ9ldsE%3D&reserved=0>

Please review and close if it looks good

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGRIDAPPSD%2FGOSS-GridAPPS-D%2Fissues%2F907%23issuecomment-892330593&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467561495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lpK2uw14OP2rbWAKJEOCl9fB0r7MhVNsLORULkX2AZo%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFSH6WA4HRHLTTPBWXISL33T3CW6ZANCNFSM4HKDHDTQ&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467561495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d8ybw3jk%2FQBdXCmDWXz5kU%2FtgZTasewPkZZbTMNZcPQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467571453%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h3IAnz8NO0HAtFZW%2FMno7%2BEqqs%2Blxa8bpnQhdRqT7OA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CJeff.Simpson%40nrel.gov%7Cb09360c74d2d458c09ca08d956f71242%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637636441467661049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FFD5medyqx%2BATzWnX%2FdXoZloGqfQgMzW%2BIPqNqEwPdQ%3D&reserved=0>.

**Comment by AAndersn** [comment]
Changes completed and pushed to rtd page
